title: Jing Yang's Homepage
page-top-title: Jing Yang
top-section-bg-text: Logic, Agents, and Reliable AI
home-subtitle: Institute of Logic and Cognition, Sun Yat-sen University
copyright-text: '&copy; Jing Yang 2026. All Rights Reserved.'
